name: CI

on:
  push:
    branches:
      - '**' # This will trigger on all branches
  pull_request:
    branches:
      - '**' # This will trigger for pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.8.0'

      - name: Install dependencies
        run: npm ci  # Use npm ci for exact versions

      - name: Run tests with coverage
        run: npm run test:coverage  # Run tests with coverage in CI

      - name: Build the project
        run: npm run build
