name: CI

on:
  push:
    branches:
      - '**' # This will trigger on all branches
  pull_request:
    branches:
      - '**' # This will trigger for pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.8.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the project
        run: npm run build
